import os
import sys
from pathlib import Path
from dotenv import load_dotenv

CREWAI_STORAGE_DIR = Path(__file__).parent / ".crewai_storage"
os.environ["CREWAI_DISABLE_TELEMETRY"] = "true"
os.environ["LITELLM_LOG"] = "ERROR"

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def local_crewai_storage_path() -> str:
    CREWAI_STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    return str(CREWAI_STORAGE_DIR)

# This prevents crewAI from embedding 'cache_breakpoint' inside messages sent to Groq.
import crewai.llms.cache as _crewai_cache
_crewai_cache.mark_cache_breakpoint = lambda msg: msg

from crewai import Agent, Task, Crew, Process, LLM
import crewai.memory.storage.kickoff_task_outputs_storage as _kickoff_storage

_kickoff_storage.db_storage_path = local_crewai_storage_path

# 1. Load the API key from the .env file
load_dotenv()

print("Booting up the Autonomous Industrial Incident Team...")

# 2. Explicitly define the Groq LLM
groq_llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    api_key=os.environ.get("GROQ_API_KEY")
)

# ==========================================
# STEP 1: DEFINE THE AGENTS
# ==========================================

data_engineer = Agent(
    role='Senior Industrial Data Engineer',
    goal='Analyze raw motor telemetry and identify statistical anomalies.',
    backstory='You have 10 years of experience reading ESP32 sensor data for 12V DC motors. You know that a healthy motor runs under 5 Amps, and any sudden spike indicates a severe issue.',
    verbose=False,
    allow_delegation=False,
    llm=groq_llm
)

diagnostic_analyst = Agent(
    role='Mechanical Diagnostic Analyst',
    goal='Determine the physical root cause of a motor fault based on data anomalies.',
    backstory='You are an expert in electromechanical systems. You translate raw numbers (like voltage drops or current spikes) into physical realities (like mechanical jams or short circuits).',
    verbose=False,
    allow_delegation=False,
    llm=groq_llm
)

operations_manager = Agent(
    role='Factory Operations Manager',
    goal='Draft a concise, actionable incident report for the maintenance team.',
    backstory='You manage the factory floor. You hate technical jargon. You need clear, bulleted reports telling your maintenance team exactly what broke and what to fix.',
    verbose=False,
    allow_delegation=False,
    llm=groq_llm
)

# ==========================================
# STEP 2: DEFINE THE TASKS
# ==========================================

simulated_telemetry = "TIMESTAMP: 14:02:11 | CURRENT: 18.5 A | VOLTAGE: 10.2 V | SPEED: 450 RPM"

task_analyze_data = Task(
    description=f'Review the following live telemetry from motor #M-404: {simulated_telemetry}. Identify if this represents a normal state or a fault.',
    expected_output='A short summary of the data highlighting any abnormal metrics.',
    agent=data_engineer
)

task_diagnose_fault = Task(
    description='Take the data engineer\'s analysis. Determine the most likely physical cause of this state (e.g., is the motor jammed? is there a short circuit?).',
    expected_output='A 2-sentence diagnosis of the root physical cause.',
    agent=diagnostic_analyst
)

task_write_report = Task(
    description='Take the diagnosis and write a final Incident Report. Include the raw data, the diagnosis, and recommended next steps for the maintenance team. Output strictly in Markdown format.',
    expected_output='A professional Markdown formatted incident report.',
    agent=operations_manager
)

# ==========================================
# STEP 3: ASSEMBLE THE CREW
# ==========================================

incident_crew = Crew(
    agents=[data_engineer, diagnostic_analyst, operations_manager],
    tasks=[task_analyze_data, task_diagnose_fault, task_write_report],
    process=Process.sequential
)

# Start the execution!
result = incident_crew.kickoff()

print("\n\n================================================")
print("FINAL OUTPUT GENERATED BY THE SYSTEM:")
print("================================================\n")
print(result)
